name: Build and Test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Lambda
        run: ./scripts/build-lambda.sh

      - name: Run Unit Tests
        run: go test -race ./...